#sdk: "/Users/lucascampbell-rossen/rhomobile/rhodes"
sdk: "/Users/lucascampbell-rossen/rhomobile/new_rhodes/rhodes"

sdkversion: 3.3.2
name: GoVerse
version: 1.5.0
vendor: JS
build: debug
bbver: 4.6
applog: rholog.txt

# iphone:
#   configuration: Debug
#   sdk: iphonesimulator5.1
#   provisionprofile:
#   codesignidentity: iPhone Developer
#   entitlements:
#   BundleIdentifier: com.christianscience.quoto
#   BundleURLScheme: quotes
  
iphone:
  configuration: Release
  sdk: iphonesimulator5.1
  provisionprofile: 
  codesignidentity: "iPhone Distribution"
  entitlements: 
  BundleIdentifier: com.christianscience.quoto
  BundleURLScheme: quotes

wp:
  productid: b47fc940-4571-012f-6616-080027fd4ea2
symbian:
  uid: 4018615533

android:
  version: 3.2.0
  android_title: 0
  push:
    sender: quotesapp.tmc@gmail.com
    notifications: always
    
capabilities:
  - push
  - vibrate
extensions:
  - json
  - another-extension
